name: "Check cypress Status"

on: [push]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "cypress/reports/output.json"
      - name: Check cypres result's file
        run: |
          if [ ${{steps.check_files.outputs.files_exists}} == 'true' ]; then
          echo "File exists!"
          else
          echo "File not exists!"
          exit 1
          fi
      - name: Get date from output.json
        id: date
        uses: notiz-dev/github-action-json-property@release
        with: 
         path: 'cypress/reports/output.json'
         prop_path: Value(stats.tests)
      - name: Check cypress report date  
        run: |
          if [ "$(date -d "${{steps.date.outputs.prop}}" +'%Y-%m-%d')" == "$(date +'%Y-%m-%d')" ]; then
          echo "Report date: $(date -d "${{steps.date.outputs.prop}}" +'%Y-%m-%d')"
          else
          echo "Cypress report and PR date not matched!"
          exit 1
          fi
      - name: Get status from output.json
        id: format_script
        uses: notiz-dev/github-action-json-property@release
        with: 
         path: 'cypress/reports/output.json'
         prop_path: 'stats.tests'
      - name: Get status from output.json
        id: passes
        uses: notiz-dev/github-action-json-property@release
        with: 
         path: 'cypress/reports/output.json'
         prop_path: 'stats.passes'
      - name: Check cypress status
        run: |
          if [ '${{steps.format_script.outputs.prop}}' == '${{steps.passes.outputs.prop}}' ]; then
          echo "All tests passed"
          else
          echo "Tests failed!"
          exit 1
          fi
