name: "File existence check"

on: [push]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "cypress/reports/output.json"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
      - name: get nested property
        id: format_script
        uses: notiz-dev/github-action-json-property@release
        with: 
         path: 'cypress/reports/output.json'
         prop_path: 'stats.tests'
      - name: Run nested property  
        if: ${{steps.format_script.outputs.prop}} == 4
        continue-on-error: true
        run: echo ${{steps.format_script.outputs.prop}}

