name: "File existence check"

on: [push]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "cypress/reports/index.html"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
      - name: Run file on browser
        run: google-chrome /home/runner/work/readme/readme/cypress/reports/index.html
      - name: get nested property
        id: format_script
        uses: notiz-dev/github-action-json-property@release
        with: 
         path: 'package.json'
         prop_path: 'scripts.production'
      - run: echo ${{steps.format_script.outputs.prop}} 
