name: Run Lint for Syntax errors

on:
  push:
    branches:
      - "master"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies 
        run: npm install
      - name: Make production build
        run: npm run prod
      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      - name: Install phplint
        run:  npm i -g phplint
      - name: Run linters
      # Run for specific file
      # run: ./node_modules/.bin/eslint  LumiereApi/app.js
      # Run for specific folder
        run: phplint app/ & ./node_modules/.bin/eslint ./

