name: Run build after Check lint 
on:
  push:
    branches:
      - "master"
  paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  phpstan:
    name: "PHP: 7.4 | PHPStan"

    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: phpstan

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"

      - name: Run PHPStan
        run: phpstan analyse --configuration=phpstan.neon