# This is a basic workflow to help you get started with Actions

name: Publish the latest draft release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        default: 'v1.0.0'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get current timestamp
        id: datetime
        run: echo "::set-output name=datetime::$(date +%Y-%m-%d-T%H:%M:%S%z)"


      - name: Publish the latest draft
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ github.event.inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Update GitHub Release
        uses: tubone24/update_release@v1.3.1
        with:
          is_append_body: true
          body: |
            ---
            Deployed on ${{ steps.datetime.outputs.datetime }} by [@${{ github.actor }}](https://github.com/${{ github.actor }}).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.inputs.release }}
